/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/pivotal/monitoring-indicator-protocol/k8s/pkg/apis/indicatordocument/v1alpha1"
	scheme "github.com/pivotal/monitoring-indicator-protocol/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IndicatorsGetter has a method to return a IndicatorInterface.
// A group's client should implement this interface.
type IndicatorsGetter interface {
	Indicators(namespace string) IndicatorInterface
}

// IndicatorInterface has methods to work with Indicator resources.
type IndicatorInterface interface {
	Create(*v1alpha1.Indicator) (*v1alpha1.Indicator, error)
	Update(*v1alpha1.Indicator) (*v1alpha1.Indicator, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Indicator, error)
	List(opts v1.ListOptions) (*v1alpha1.IndicatorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Indicator, err error)
	IndicatorExpansion
}

// indicators implements IndicatorInterface
type indicators struct {
	client rest.Interface
	ns     string
}

// newIndicators returns a Indicators
func newIndicators(c *AppsV1alpha1Client, namespace string) *indicators {
	return &indicators{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the indicator, and returns the corresponding indicator object, and an error if there is any.
func (c *indicators) Get(name string, options v1.GetOptions) (result *v1alpha1.Indicator, err error) {
	result = &v1alpha1.Indicator{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("indicators").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Indicators that match those selectors.
func (c *indicators) List(opts v1.ListOptions) (result *v1alpha1.IndicatorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IndicatorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("indicators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested indicators.
func (c *indicators) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("indicators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a indicator and creates it.  Returns the server's representation of the indicator, and an error, if there is any.
func (c *indicators) Create(indicator *v1alpha1.Indicator) (result *v1alpha1.Indicator, err error) {
	result = &v1alpha1.Indicator{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("indicators").
		Body(indicator).
		Do().
		Into(result)
	return
}

// Update takes the representation of a indicator and updates it. Returns the server's representation of the indicator, and an error, if there is any.
func (c *indicators) Update(indicator *v1alpha1.Indicator) (result *v1alpha1.Indicator, err error) {
	result = &v1alpha1.Indicator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("indicators").
		Name(indicator.Name).
		Body(indicator).
		Do().
		Into(result)
	return
}

// Delete takes name of the indicator and deletes it. Returns an error if one occurs.
func (c *indicators) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("indicators").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *indicators) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("indicators").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched indicator.
func (c *indicators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Indicator, err error) {
	result = &v1alpha1.Indicator{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("indicators").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
