package docs

import (
	"github.com/pivotal/monitoring-indicator-protocol/pkg/indicator"
	"html/template"
)

const bookbinderDocumentTemplate = `---
title: {{.Title}}
owner: {{.Owner}}
warning: This file is auto-generated by github.com/pivotal/monitoring-indicator-protocol. Any changes will likely be overwritten. Edit the associated indicators yaml file to make changes.
---

{{.Description}}

{{range .Sections}}
## <a id="{{.TitleID}}"></a>{{.Title}}
{{.Description}}

{{range .HTMLIndicators}}
### <a id="{{.Name}}"></a>{{.Title}} 
{{.HTML}}
{{- end}}
		
{{- end}}
`

var bookbinderDocumatationTmpl = template.Must(template.New("bookbinder_document").Parse(bookbinderDocumentTemplate))
func DocumentToBookbinder(d indicator.Document) (string, error) {
	return docToTemplate(d, bookbinderDocumatationTmpl)
}
