package docs

const htmlDocumentTemplate = `---
title: {{.Title}}
owner: {{.Owner}}
warning: This file is auto-generated by code.cloudfoundry.org/indicators. Any changes will likely be overwritten. Edit the associated indicators yaml file to make changes.
---

{{.Description}}

{{range .Sections}}
## <a id="{{.TitleID}}"></a>{{.Title}}
{{.Description}}

{{range .HTMLIndicators}}
{{.}}
{{end}}
		
{{end}}
`

const htmlIndicatorTemplate = `### <a id="{{.Name}}"></a>{{.Title}}
<table>
    <tr>
        <th width="25%">Description</th>
        <td>{{.Description}}</td>
    </tr>
    <tr>
        <th>PromQL</th>
        <td>
			<code>{{.PromQL}}</code>
		</td>
    </tr>
    <tr>
        <th>Thresholds</th>
        <td>
            {{range .Thresholds}} <em>{{.Level}}</em>: {{.OperatorAndValue}}<br/> {{end}}
			      {{if ne .ThresholdNote ""}}
			      	{{.ThresholdNote}}
			      {{end}}
        </td>
    </tr>
	{{range $key, $value :=.OtherDocumentationFields}}
    	<tr>
    	    <th>{{$key}}</th>
    	    <td>
    	        {{$value}}
    	    </td>
    	</tr>
	{{end}}
</table>`
