// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	indicatordocumentv1alpha1 "github.com/pivotal/monitoring-indicator-protocol/pkg/k8s/apis/indicatordocument/v1alpha1"
	versioned "github.com/pivotal/monitoring-indicator-protocol/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/pivotal/monitoring-indicator-protocol/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/pivotal/monitoring-indicator-protocol/pkg/k8s/client/listers/indicatordocument/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IndicatorDocumentInformer provides access to a shared informer and lister for
// IndicatorDocuments.
type IndicatorDocumentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IndicatorDocumentLister
}

type indicatorDocumentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIndicatorDocumentInformer constructs a new informer for IndicatorDocument type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIndicatorDocumentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIndicatorDocumentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIndicatorDocumentInformer constructs a new informer for IndicatorDocument type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIndicatorDocumentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha1().IndicatorDocuments(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha1().IndicatorDocuments(namespace).Watch(options)
			},
		},
		&indicatordocumentv1alpha1.IndicatorDocument{},
		resyncPeriod,
		indexers,
	)
}

func (f *indicatorDocumentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIndicatorDocumentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *indicatorDocumentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&indicatordocumentv1alpha1.IndicatorDocument{}, f.defaultInformer)
}

func (f *indicatorDocumentInformer) Lister() v1alpha1.IndicatorDocumentLister {
	return v1alpha1.NewIndicatorDocumentLister(f.Informer().GetIndexer())
}
