// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	indicatordocumentv1alpha1 "github.com/pivotal/monitoring-indicator-protocol/k8s/pkg/apis/indicatordocument/v1alpha1"
	versioned "github.com/pivotal/monitoring-indicator-protocol/k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/pivotal/monitoring-indicator-protocol/k8s/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/pivotal/monitoring-indicator-protocol/k8s/pkg/client/listers/indicatordocument/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IndicatorInformer provides access to a shared informer and lister for
// Indicators.
type IndicatorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IndicatorLister
}

type indicatorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIndicatorInformer constructs a new informer for Indicator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIndicatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIndicatorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIndicatorInformer constructs a new informer for Indicator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIndicatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha1().Indicators(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha1().Indicators(namespace).Watch(options)
			},
		},
		&indicatordocumentv1alpha1.Indicator{},
		resyncPeriod,
		indexers,
	)
}

func (f *indicatorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIndicatorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *indicatorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&indicatordocumentv1alpha1.Indicator{}, f.defaultInformer)
}

func (f *indicatorInformer) Lister() v1alpha1.IndicatorLister {
	return v1alpha1.NewIndicatorLister(f.Informer().GetIndexer())
}
