// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/pivotal/monitoring-indicator-protocol/k8s/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Indicators returns a IndicatorInformer.
	Indicators() IndicatorInformer
	// IndicatorDocuments returns a IndicatorDocumentInformer.
	IndicatorDocuments() IndicatorDocumentInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Indicators returns a IndicatorInformer.
func (v *version) Indicators() IndicatorInformer {
	return &indicatorInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IndicatorDocuments returns a IndicatorDocumentInformer.
func (v *version) IndicatorDocuments() IndicatorDocumentInformer {
	return &indicatorDocumentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
