// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/pivotal/monitoring-indicator-protocol/pkg/k8s/apis/indicatordocument/v1"
	scheme "github.com/pivotal/monitoring-indicator-protocol/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IndicatorDocumentsGetter has a method to return a IndicatorDocumentInterface.
// A group's client should implement this interface.
type IndicatorDocumentsGetter interface {
	IndicatorDocuments(namespace string) IndicatorDocumentInterface
}

// IndicatorDocumentInterface has methods to work with IndicatorDocument resources.
type IndicatorDocumentInterface interface {
	Create(*v1.IndicatorDocument) (*v1.IndicatorDocument, error)
	Update(*v1.IndicatorDocument) (*v1.IndicatorDocument, error)
	UpdateStatus(*v1.IndicatorDocument) (*v1.IndicatorDocument, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.IndicatorDocument, error)
	List(opts metav1.ListOptions) (*v1.IndicatorDocumentList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.IndicatorDocument, err error)
	IndicatorDocumentExpansion
}

// indicatorDocuments implements IndicatorDocumentInterface
type indicatorDocuments struct {
	client rest.Interface
	ns     string
}

// newIndicatorDocuments returns a IndicatorDocuments
func newIndicatorDocuments(c *AppsV1Client, namespace string) *indicatorDocuments {
	return &indicatorDocuments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the indicatorDocument, and returns the corresponding indicatorDocument object, and an error if there is any.
func (c *indicatorDocuments) Get(name string, options metav1.GetOptions) (result *v1.IndicatorDocument, err error) {
	result = &v1.IndicatorDocument{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("indicatordocuments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IndicatorDocuments that match those selectors.
func (c *indicatorDocuments) List(opts metav1.ListOptions) (result *v1.IndicatorDocumentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.IndicatorDocumentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("indicatordocuments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested indicatorDocuments.
func (c *indicatorDocuments) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("indicatordocuments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a indicatorDocument and creates it.  Returns the server's representation of the indicatorDocument, and an error, if there is any.
func (c *indicatorDocuments) Create(indicatorDocument *v1.IndicatorDocument) (result *v1.IndicatorDocument, err error) {
	result = &v1.IndicatorDocument{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("indicatordocuments").
		Body(indicatorDocument).
		Do().
		Into(result)
	return
}

// Update takes the representation of a indicatorDocument and updates it. Returns the server's representation of the indicatorDocument, and an error, if there is any.
func (c *indicatorDocuments) Update(indicatorDocument *v1.IndicatorDocument) (result *v1.IndicatorDocument, err error) {
	result = &v1.IndicatorDocument{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("indicatordocuments").
		Name(indicatorDocument.Name).
		Body(indicatorDocument).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *indicatorDocuments) UpdateStatus(indicatorDocument *v1.IndicatorDocument) (result *v1.IndicatorDocument, err error) {
	result = &v1.IndicatorDocument{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("indicatordocuments").
		Name(indicatorDocument.Name).
		SubResource("status").
		Body(indicatorDocument).
		Do().
		Into(result)
	return
}

// Delete takes name of the indicatorDocument and deletes it. Returns an error if one occurs.
func (c *indicatorDocuments) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("indicatordocuments").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *indicatorDocuments) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("indicatordocuments").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched indicatorDocument.
func (c *indicatorDocuments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.IndicatorDocument, err error) {
	result = &v1.IndicatorDocument{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("indicatordocuments").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
