// Code generated by lister-gen. DO NOT EDIT.

package v1

// IndicatorListerExpansion allows custom methods to be added to
// IndicatorLister.
type IndicatorListerExpansion interface{}

// IndicatorNamespaceListerExpansion allows custom methods to be added to
// IndicatorNamespaceLister.
type IndicatorNamespaceListerExpansion interface{}

// IndicatorDocumentListerExpansion allows custom methods to be added to
// IndicatorDocumentLister.
type IndicatorDocumentListerExpansion interface{}

// IndicatorDocumentNamespaceListerExpansion allows custom methods to be added to
// IndicatorDocumentNamespaceLister.
type IndicatorDocumentNamespaceListerExpansion interface{}
