// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pivotal/monitoring-indicator-protocol/k8s/pkg/apis/indicatordocument/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIndicatorDocuments implements IndicatorDocumentInterface
type FakeIndicatorDocuments struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var indicatordocumentsResource = schema.GroupVersionResource{Group: "apps.pivotal.io", Version: "v1alpha1", Resource: "indicatordocuments"}

var indicatordocumentsKind = schema.GroupVersionKind{Group: "apps.pivotal.io", Version: "v1alpha1", Kind: "IndicatorDocument"}

// Get takes name of the indicatorDocument, and returns the corresponding indicatorDocument object, and an error if there is any.
func (c *FakeIndicatorDocuments) Get(name string, options v1.GetOptions) (result *v1alpha1.IndicatorDocument, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(indicatordocumentsResource, c.ns, name), &v1alpha1.IndicatorDocument{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndicatorDocument), err
}

// List takes label and field selectors, and returns the list of IndicatorDocuments that match those selectors.
func (c *FakeIndicatorDocuments) List(opts v1.ListOptions) (result *v1alpha1.IndicatorDocumentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(indicatordocumentsResource, indicatordocumentsKind, c.ns, opts), &v1alpha1.IndicatorDocumentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IndicatorDocumentList{ListMeta: obj.(*v1alpha1.IndicatorDocumentList).ListMeta}
	for _, item := range obj.(*v1alpha1.IndicatorDocumentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested indicatorDocuments.
func (c *FakeIndicatorDocuments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(indicatordocumentsResource, c.ns, opts))

}

// Create takes the representation of a indicatorDocument and creates it.  Returns the server's representation of the indicatorDocument, and an error, if there is any.
func (c *FakeIndicatorDocuments) Create(indicatorDocument *v1alpha1.IndicatorDocument) (result *v1alpha1.IndicatorDocument, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(indicatordocumentsResource, c.ns, indicatorDocument), &v1alpha1.IndicatorDocument{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndicatorDocument), err
}

// Update takes the representation of a indicatorDocument and updates it. Returns the server's representation of the indicatorDocument, and an error, if there is any.
func (c *FakeIndicatorDocuments) Update(indicatorDocument *v1alpha1.IndicatorDocument) (result *v1alpha1.IndicatorDocument, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(indicatordocumentsResource, c.ns, indicatorDocument), &v1alpha1.IndicatorDocument{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndicatorDocument), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIndicatorDocuments) UpdateStatus(indicatorDocument *v1alpha1.IndicatorDocument) (*v1alpha1.IndicatorDocument, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(indicatordocumentsResource, "status", c.ns, indicatorDocument), &v1alpha1.IndicatorDocument{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndicatorDocument), err
}

// Delete takes name of the indicatorDocument and deletes it. Returns an error if one occurs.
func (c *FakeIndicatorDocuments) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(indicatordocumentsResource, c.ns, name), &v1alpha1.IndicatorDocument{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIndicatorDocuments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(indicatordocumentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.IndicatorDocumentList{})
	return err
}

// Patch applies the patch and returns the patched indicatorDocument.
func (c *FakeIndicatorDocuments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IndicatorDocument, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(indicatordocumentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IndicatorDocument{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndicatorDocument), err
}
